---
version: 3

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:latest

dependencies:
  ansible_runner:
    package_pip: ansible-runner

  galaxy: requirements.yml
      
  python: requirements.txt

  system: bindep.txt
