name: publish
on: [push]
jobs:
  publish-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Print podman version
        run: podman version

      - name: Install ansible-builder
        run: python3 -m pip install ansible-builder

      - name: Build and publish final image
        run: |
          ansible-builder build -f $GITHUB_WORKSPACE/execution-environment.yml -t ghcr.io/nilashishc/network-ee:latest -v3
          podman push ghcr.io/nilashishc/network-ee:latest
